version: '3.3'

services:
  web:
    image: itzg/rcon
    container_name: mcweb
    environment:
      RWA_USERNAME: "monga"
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: "mcserver"
      RWA_RCON_PASSWORD: "demo"

  mcserver:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    environment:
      MEMORYSIZE: '1G'
      PAPERMC_FLAGS: ''
	  TZ: 'BR'
    volumes:
      - ./data:/data:rw
    ports:
      - "25565:25565"
