version: '3.3'
services:
  mc-panel:
    image: itzg/rcon
    container_name: mc-panel
    networks:
      - game-server
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mcserver
      RWA_RCON_PASSWORD: "monga"
    ports:
      - "4326:4326"
      - "4327:4327"
  mc-server:
    image: marctv/minecraft-papermc-server:latest
    container_name: mc-server
    networks:
      - game-server
    restart: unless-stopped
    environment:
      MEMORYSIZE: '1G'
      PAPERMC_FLAGS: ''
      TZ: 'BR'
    volumes:
      - ./data:/data:rw
    ports:
      - "25565:25565"
networks:
  game-server:
